@Redis_OM_Migrations_API_HostAddress = http://localhost:5260

GET {{Redis_OM_Migrations_API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Redis_OM_Migrations_API_HostAddress}}/user/
Accept: application/json

###

POST {{Redis_OM_Migrations_API_HostAddress}}/user/index/
Accept: application/json

###

POST {{Redis_OM_Migrations_API_HostAddress}}/user/
Accept: application/json

###

POST {{Redis_OM_Migrations_API_HostAddress}}/migration/
Accept: application/json

###

POST {{Redis_OM_Migrations_API_HostAddress}}/snapshot/
Accept: application/json

###

GET {{Redis_OM_Migrations_API_HostAddress}}/aes-key/
Accept: application/json

###

POST {{Redis_OM_Migrations_API_HostAddress}}/encrypt
Accept: application/json

###

POST {{Redis_OM_Migrations_API_HostAddress}}/encrypt/text?message=Hello People!
Accept: application/json

###

POST {{Redis_OM_Migrations_API_HostAddress}}/encrypt/package/text?message=Hello People!
Accept: application/json

###

POST {{Redis_OM_Migrations_API_HostAddress}}/decrypt
Accept: application/json

###

POST {{Redis_OM_Migrations_API_HostAddress}}/decrypt/text
Accept: application/json
Content-Type: application/json

{
  "base64EncodedEncryptedText": "+Ndi1vcrdxRQ2I0Rhg==",
  "iv": "+C4Hrd76badPpo2V",
  "tag": "sapJaIt7Exho5ZLFg6/cYg=="
}
###

POST {{Redis_OM_Migrations_API_HostAddress}}/decrypt/package/text
Accept: application/json
Content-Type: application/json

{
  "base64EncryptedPackage": "ZzEk6I2AtFyg43LUtbxQueJml5ETcc3A0IKJXTL2jFlWU51eslL/UyA="
}
###